POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Jack Daniels",
  "dateOfBirth": "1949-01-10",
  "ssn": "100149-05Z",
  "gender": "male",
  "occupation": "Whiskey",
  "entries": {
    "date": "2020-10-20",
    "specialist": "MD House",
    "type": "OccupationalHealthcare",
    "employerName": "FBI",
    "description": "Prescriptions renewed."
  }
}