POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Novichok",
    "author": "Vladimir Putin",
    "url": "http://novichok.com/",
    "likes": 66,
    "userId": "5f5b85ec9355c029ec83acdd"
}