POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhbHlvdmthIiwiaWQiOiI1ZjViODVlYzkzNTVjMDI5ZWM4M2FjZGQiLCJpYXQiOjE2MDAxNjc1NTh9.aHAz9GuhXjr7N_ewYUwpOvSRcJfOAaLpgqRewYAjy2E

{
    "title": "Test authorization",
    "author": "Other User",
    "url": "http://testauthorization.com/",
    "likes": 44
}