POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "nollata",
    "author": "null null",
    "url": "http://nuull.com/",
    "likes": 23,
    "userId": "5ef32004cfce7413f644eded"
}